# Generated by Django 3.2.21 on 2025-06-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('guest_count', models.IntegerField()),
                ('reservation_time', models.DateField(auto_now=True)),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='precio',
            new_name='price',
        ),
    ]
